name: Run D.A.I.S.Y

on:
  push:
    branches:
      - main
      - feature/github-action

jobs:
  daisy:
    name: Daisy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Node.js 18
        uses: actions/setup-node@master
        with:
          node-version: 18

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Turbo Cache
        id: turbo-cache
        uses: actions/cache@v2
        with:
          path: node_modules/.cache/turbo
          key: turbo-${{ github.job }}-${{ github.ref_name }}-${{ github.sha }}
          restore-keys: |
            turbo-${{ github.job }}-${{ github.ref_name }}-

      - name: Build
        id: build
        run: pnpm build

      - name: Install dependencies
        run: pnpm install

      - name: Runs daisy completions or memorizations
        id: daisy
        uses: ./packages/github-action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ANSWERAI_API_KEY: ${{ secrets.ANSWERAI_API_KEY }}
